import { Scholarship } from '../types'

export const scholarshipsMock: Scholarship[] = [
  {
    id: 'horizonte-stem',
    title: 'Bolsa Horizonte STEM',
    provider: 'Fundação Horizonte',
    location: 'Maputo, Moçambique',
    modality: 'Presencial',
    level: 'Licenciatura',
    field: 'Engenharia e TIC',
    type: 'Mérito',
    coverage: ['Propina', 'Alojamento', 'Livros'],
    amountRange: 'MZN 8.000/mês + alojamento',
    maxAmount: 8000,
    deadline: '2024-06-15',
    language: 'Português',
    country: 'Moçambique',
    publishedAt: '2024-04-05',
    recommended: true,
    tags: ['Mulheres em STEM'],
  },
  {
    id: 'moztech-codigo',
    title: 'Tech Mulheres em Código',
    provider: 'MozTech',
    location: 'Online · Moçambique',
    modality: 'Online',
    level: 'Bootcamp',
    field: 'Tecnologia',
    type: 'Diversidade',
    coverage: ['Propina', 'Bolsa mensal', 'Livros'],
    amountRange: 'MZN 6.500/mês',
    maxAmount: 6500,
    deadline: '2024-05-28',
    language: 'Português',
    country: 'Moçambique',
    publishedAt: '2024-04-22',
    tags: ['Programa intensivo', 'Mentoria'],
  },
  {
    id: 'impacto-comunitario',
    title: 'Bolsa Impacto Comunitário',
    provider: 'Fundação Impacto+',
    location: 'Beira, Moçambique',
    modality: 'Híbrido',
    level: 'Licenciatura',
    field: 'Ciências Sociais',
    type: 'Necessidade',
    coverage: ['Propina', 'Alimentação', 'Transporte'],
    amountRange: 'MZN 7.200/mês',
    maxAmount: 7200,
    deadline: '2024-07-05',
    language: 'Português',
    country: 'Moçambique',
    publishedAt: '2024-03-18',
    recommended: true,
    tags: ['Serviço comunitário'],
  },
  {
    id: 'pesquisa-africa',
    title: 'Pesquisa para África',
    provider: 'CPLP Labs',
    location: 'Pretória, África do Sul',
    modality: 'Presencial',
    level: 'Mestrado',
    field: 'Saúde e Biotecnologia',
    type: 'Pesquisa',
    coverage: ['Propina', 'Bolsa mensal', 'Viagem', 'Livros'],
    amountRange: 'MZN 9.500/mês',
    maxAmount: 9500,
    deadline: '2024-06-02',
    language: 'Inglês',
    country: 'África do Sul',
    publishedAt: '2024-04-10',
    tags: ['Mobilidade', 'Laboratórios parceiros'],
  },
  {
    id: 'atleta-academico',
    title: 'Atleta Académico',
    provider: 'UniLuz',
    location: 'Nampula, Moçambique',
    modality: 'Presencial',
    level: 'Licenciatura',
    field: 'Educação Física',
    type: 'Atleta',
    coverage: ['Propina', 'Alojamento', 'Alimentação'],
    amountRange: 'MZN 6.800/mês',
    maxAmount: 6800,
    deadline: '2024-08-12',
    language: 'Português',
    country: 'Moçambique',
    publishedAt: '2024-02-28',
    tags: ['Equipa universitária'],
  },
  {
    id: 'futuro-verde',
    title: 'Futuro Verde',
    provider: 'EarthMoZ',
    location: 'Online · Internacional',
    modality: 'Online',
    level: 'Pós-Graduação',
    field: 'Ambiente e Sustentabilidade',
    type: 'Internacional',
    coverage: ['Propina', 'Livros'],
    amountRange: 'MZN 5.200/mês',
    maxAmount: 5200,
    deadline: '2024-05-18',
    language: 'Bilingue',
    country: 'Global',
    publishedAt: '2024-04-30',
    tags: ['Clima', 'Projecto aplicado'],
  },
]
