import { University } from './types'

export const universitiesMock: University[] = [
  {
    id: 'isctem',
    name: 'Instituto Superior de Ciências e Tecnologia de Moçambique',
    location: 'Maputo, Moçambique',
    country: 'Moçambique',
    type: 'Pública',
    modality: 'Campus',
    fields: ['Engenharia', 'Tecnologia', 'Gestão'],
    tuitionRange: 'MZN 6.800 - 8.500 / semestre',
    maxTuition: 8500,
    deadline: '2024-05-15',
    rating: 4.6,
    tags: ['Laboratórios modernos', 'On-campus'],
  },
  {
    id: 'unilurio',
    name: 'Universidade Lúrio',
    location: 'Nampula, Moçambique',
    country: 'Moçambique',
    type: 'Pública',
    modality: 'Híbrida',
    fields: ['Saúde', 'Engenharia', 'Agrárias'],
    tuitionRange: 'MZN 5.200 - 7.000 / semestre',
    maxTuition: 7000,
    deadline: '2024-06-01',
    rating: 4.2,
    tags: ['Mobilidade', 'Híbrida'],
  },
  {
    id: 'unizambeze',
    name: 'Universidade Zambeze',
    location: 'Beira, Moçambique',
    country: 'Moçambique',
    type: 'Pública',
    modality: 'Campus',
    fields: ['Direito', 'Economia', 'Saúde'],
    tuitionRange: 'MZN 4.800 - 6.500 / semestre',
    maxTuition: 6500,
    deadline: '2024-05-28',
    rating: 4.1,
    tags: ['Pesquisa aplicada'],
  },
  {
    id: 'uam',
    name: 'Universidade Autónoma de Moçambique',
    location: 'Maputo, Moçambique',
    country: 'Moçambique',
    type: 'Privada',
    modality: 'Online',
    fields: ['Gestão', 'Tecnologia', 'Direito'],
    tuitionRange: 'MZN 3.900 - 5.500 / semestre',
    maxTuition: 5500,
    deadline: '2024-06-20',
    rating: 4.0,
    tags: ['Online', 'Flexível'],
  },
  {
    id: 'ustm',
    name: 'Universidade São Tomás de Moçambique',
    location: 'Maputo, Moçambique',
    country: 'Moçambique',
    type: 'Privada',
    modality: 'Campus',
    fields: ['Humanidades', 'Gestão', 'Comunicação'],
    tuitionRange: 'MZN 4.200 - 6.200 / semestre',
    maxTuition: 6200,
    deadline: '2024-07-05',
    rating: 3.9,
    tags: ['Clubs estudantis'],
  },
  {
    id: 'upungue',
    name: 'Universidade Púnguè',
    location: 'Chimoio, Moçambique',
    country: 'Moçambique',
    type: 'Pública',
    modality: 'Híbrida',
    fields: ['Agrárias', 'Engenharia', 'Ciências Sociais'],
    tuitionRange: 'MZN 4.000 - 5.600 / semestre',
    maxTuition: 5600,
    deadline: '2024-05-10',
    rating: 4.3,
    tags: ['Projectos comunitários'],
  },
]
